In [1]:
import numpy as np
import matplotlib.pyplot as plt

from IPython.display import clear_output
import time

# 送出題目

In [6]:
# 打亂1~9的數字array
series = np.arange(1, 9+1)
np.random.shuffle(series)

# 正確答案
ans = np.arange(1, 9+1)

# array轉成list，以便之後while的判斷為一個布林值
matlist = series.tolist()
anslist = ans.tolist()

# 題目產生
print(series.reshape(3, 3))

[[6 7 4]
 [1 3 5]
 [9 8 2]]


# 遊戲開始
## 遊戲規則
* 數字9可與其上下左右的數字交換(按鍵wsad對應上下左右)
* 利用此規則使數字拼圖能按照順序排列即可過關
* 欲離開遊戲，請輸入exit

In [7]:
step = 0
while matlist != anslist:
    
    # 刪除上一次loop的圖片
    clear_output(wait=True)
    
    # mat轉為矩陣形式
    mat = np.array(matlist)
    mat = mat.reshape(3, 3)

    # 輸入input數字
    turn = input("方向：")
    
    # 離開指令
    if turn == "exit":
        break
        
    # 判斷執行的動作
    spaceindex = np.argwhere(mat == 9)
    spaceindex_x = spaceindex[0, 0]
    spaceindex_y = spaceindex[0, 1]
    if (turn == "w") | (turn == "s") | (turn == "a") | (turn == "d"):
        
        # 上鍵設定
        if turn == "w":
            if spaceindex_x == 2:
                print("輸入無效")
            else:
                changeindex_x = spaceindex_x+1
                changeindex_y = spaceindex_y
                mat[spaceindex_x, spaceindex_y] = mat[changeindex_x, changeindex_y]
                mat[changeindex_x, changeindex_y] = 9 
        
        # 下鍵設定
        if turn == "s":
            if spaceindex_x == 0:
                print("輸入無效")
            else:
                changeindex_x = spaceindex_x-1
                changeindex_y = spaceindex_y
                mat[spaceindex_x, spaceindex_y] = mat[changeindex_x, changeindex_y]
                mat[changeindex_x, changeindex_y] = 9 

        # 左鍵設定
        if turn == "a":
            if spaceindex_y == 2:
                print("輸入無效")
            else:
                changeindex_x = spaceindex_x
                changeindex_y = spaceindex_y+1
                mat[spaceindex_x, spaceindex_y] = mat[changeindex_x, changeindex_y]
                mat[changeindex_x, changeindex_y] = 9 

        # 右鍵設定
        if turn == "d":
            if spaceindex_y == 0:
                print("輸入無效")
            else:
                changeindex_x = spaceindex_x
                changeindex_y = spaceindex_y-1
                mat[spaceindex_x, spaceindex_y] = mat[changeindex_x, changeindex_y]
                mat[changeindex_x, changeindex_y] = 9 
    else:
        print("輸入無效")
    
    step = step+1
    print(f"第{step}步")
    print(mat)
    
    # mat 轉為list形式
    mat = mat.reshape(9)
    matlist = mat.tolist()

if matlist != anslist:
    print("離開")    
    
if matlist == anslist:
    print("恭喜過關!!!")


方向：w
第30步
[[1 2 3]
 [4 5 6]
 [7 8 9]]
恭喜過關!!!
